// Copy and Paste this code inside your pubspec.yaml file
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.5.2
  image_picker: ^1.2.0
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  fluttertoast: ^9.0.0