// copy and paste this code in your pubspec.yaml file
  dependencies: 
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    http: ^1.5.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.0.15
  
  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.6