// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83pAOQL_JUqnapksnQtF1Cz3MnQ5VCt4',
    appId: '1:406922888237:android:0ddc05a77140dab360a4a4',
    messagingSenderId: '406922888237',
    projectId: 'practice-firebase-2025-09-30',
    databaseURL: 'https://practice-firebase-2025-09-30-default-rtdb.firebaseio.com',
    storageBucket: 'practice-firebase-2025-09-30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNsdktzYmL0wYkqyOHMYbOTdLzaxTjhZE',
    appId: '1:406922888237:ios:21cddc1c67998e2a60a4a4',
    messagingSenderId: '406922888237',
    projectId: 'practice-firebase-2025-09-30',
    databaseURL: 'https://practice-firebase-2025-09-30-default-rtdb.firebaseio.com',
    storageBucket: 'practice-firebase-2025-09-30.firebasestorage.app',
    iosBundleId: 'com.example.practicingFirebase',
  );
}
